# Generated by Django 4.2.16 on 2024-09-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Landing',
            new_name='Contact',
        ),
    ]
